name: Export Electronics

on: [push]

jobs:
  export-electronics:
      name: Export Electronics
      runs-on: ubuntu-22.04
      env:
        PROJECT: odri-power-board
      steps:
      - uses: actions/checkout@v3
      - uses: actions-for-kicad/setup-kicad@v1.0
        with:
          version: "8.0"
      - uses: actions-for-kicad/generate-kicad-files@v1.0
        with:
          type: schematic_pdf
          file: hardware/${{ env.PROJECT }}.kicad_sch
      - uses: actions-for-kicad/generate-kicad-files@v1.0
        with:
          type: schematic_svg
          file: hardware/${{ env.PROJECT }}.kicad_sch
      - uses: actions-for-kicad/generate-kicad-files@v1.0
        with:
          type: schematic_bom
          file: hardware/${{ env.PROJECT }}.kicad_sch
      - name: Upload BOM
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.PROJECT }}-bom.xml
          path: ./${{ env.PROJECT }}-bom.xml
      - name: Upload Schematic
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.PROJECT }}.pdf
          path: ./${{ env.PROJECT }}.pdf
